require('dotenv').config();
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const jwt = require('jsonwebtoken');
const deepseekService = require('./src/services/deepseekService');
const selfLearningService = require('./src/services/selfLearningService');

// Create Express app
const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(cors({
  origin: ['http://localhost:5173', 'http://127.0.0.1:5173'],
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));

// Log all requests for debugging
app.use((req, res, next) => {
  console.log(`${req.method} ${req.url}`);
  next();
});

// Simple authentication middleware that always passes
const authMiddleware = (req, res, next) => {
  console.log('Auth middleware: bypassing authentication');
  next();
};

// Routes
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date() });
});

// Login route
app.post('/api/auth/login', (req, res) => {
  const { username, password } = req.body;

  // Simple authentication for testing
  if (username === 'test' && password === 'test') {
    const token = jwt.sign(
      { userId: 'test-user-id', username: 'test' },
      process.env.JWT_SECRET || 'your-secret-key',
      { expiresIn: '24h' }
    );

    return res.json({ token });
  }

  res.status(401).json({ message: 'Invalid credentials' });
});

// Query route
app.post('/api/query', authMiddleware, async (req, res) => {
  try {
    const { query, collection = 'events', schemaInfo, conversationId } = req.body;

    if (!query) {
      return res.status(400).json({ message: 'Query is required' });
    }

    console.log('Processing query:', query);
    console.log('Collection:', collection);
    console.log('Schema Info:', schemaInfo);

    // Process the query through DeepSeek
    const deepseekResponse = await deepseekService.processQuery(
      query, collection, schemaInfo, conversationId
    );
    console.log('Deepseek Response:', deepseekResponse);

    // Parse the pipeline from the Deepseek response
    let pipeline;
    let explanation = 'MongoDB aggregation pipeline generated by Deepseek LLM';
    
    try {
      // Try to parse the content as a JSON array
      pipeline = JSON.parse(deepseekResponse.content);
      console.log('Successfully parsed Deepseek response as JSON');
      
      // Ensure it's an array
      if (!Array.isArray(pipeline)) {
        console.warn('Parsed pipeline is not an array:', typeof pipeline);
        // If it's not an array but an object with a pipeline property, use that
        if (pipeline && pipeline.pipeline && Array.isArray(pipeline.pipeline)) {
          pipeline = pipeline.pipeline;
          console.log('Using pipeline property from response');
        } else {
          console.warn('Using fallback empty pipeline');
          pipeline = [{ $match: {} }, { $limit: 20 }];
        }
      }
    } catch (parseError) {
      console.error('Error parsing Deepseek response as JSON:', parseError.message);
      console.log('Raw Deepseek response:', deepseekResponse.content);
      
      // Try to extract a JSON array from the content using regex
      const jsonMatch = deepseekResponse.content.match(/\\[\\s*\\{.*\\}\\s*\\]/s);
      if (jsonMatch) {
        try {
          pipeline = JSON.parse(jsonMatch[0]);
          console.log('Successfully extracted and parsed JSON from response');
        } catch (extractError) {
          console.error('Error parsing extracted JSON:', extractError.message);
          pipeline = [{ $match: {} }, { $limit: 20 }];
        }
      } else {
        console.warn('Could not extract JSON array from response, using fallback');
        pipeline = [{ $match: {} }, { $limit: 20 }];
      }
    }
    
    // Get the database connection
    const db = mongoose.connection.db;
    const mongoCollection = db.collection(collection);

    // Execute the query
    console.log('Executing pipeline:', JSON.stringify(pipeline));
    const results = await mongoCollection.aggregate(pipeline).toArray();
    console.log(`Query returned ${results.length} results`);

    // Return response with all the fields needed for debug info
    res.json({
      query,
      timestamp: new Date(),
      results,
      processedQuery: deepseekResponse.content,
      pipeline: pipeline,
      explanation: explanation,
      tokenUsage: deepseekResponse.tokenUsage,
      conversationId: deepseekResponse.conversationId
    });
  } catch (error) {
    console.error('Query execution error:', error);
    res.status(500).json({ message: 'Query execution failed', error: error.message });
  }
});

// Connect to MongoDB
console.log('Connecting to MongoDB...');
mongoose.connect(process.env.MONGODB_URI)
  .then(() => {
    console.log('Connected to MongoDB');
    
    // Start the server
    app.listen(PORT, () => {
      console.log(`Server running on port ${PORT}`);
    });
  })
  .catch(err => {
    console.error('MongoDB connection error:', err);
    process.exit(1);
  });
